# Imagem Base
FROM python:3.9

# Pasta de trabalho
WORKDIR /app

# Copiando script
COPY consumer.py /app

# Instalando dependências
RUN pip install kafka-python faker

# Rodando script
CMD ["python", "consumer.py"]